-- Student Feedback Analyzer Database Schema
-- Run this file in MySQL Workbench or CLI: source schema.sql;

CREATE DATABASE IF NOT EXISTS student_feedback_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE student_feedback_db;

DROP TABLE IF EXISTS feedbacks;
DROP TABLE IF EXISTS users;

-- ─── Users Table ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
  id        INT AUTO_INCREMENT PRIMARY KEY,
  name      VARCHAR(100)     NOT NULL,
  email     VARCHAR(150)     NOT NULL UNIQUE,
  password  VARCHAR(255)     NOT NULL,
  role      ENUM('teacher','admin') NOT NULL DEFAULT 'teacher',
  courses   JSON             DEFAULT NULL COMMENT 'Array of course codes assigned to this teacher',
  created_at DATETIME        DEFAULT CURRENT_TIMESTAMP,

  INDEX idx_email (email),
  INDEX idx_role  (role)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ─── Feedbacks Table ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS feedbacks (
  id              INT AUTO_INCREMENT PRIMARY KEY,
  student_name    VARCHAR(100)     NOT NULL,
  student_id      VARCHAR(50)      NOT NULL,
  course          VARCHAR(50)      NOT NULL,
  instructor      VARCHAR(100)     NOT NULL,
  category        VARCHAR(50)      NOT NULL,
  rating          TINYINT UNSIGNED NOT NULL CHECK (rating BETWEEN 1 AND 5),
  feedback_text   TEXT             NOT NULL,
  is_anonymous    TINYINT(1)       DEFAULT 1,

  -- 10 individual rating questions (1-5 scale)
  q1  TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Course plan info on objectives, contents, evaluation',
  q2  TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Tests/exams covering taught material',
  q3  TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Teaching skills of instructor',
  q4  TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Clarity in speech, concepts, presentation',
  q5  TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Quality of blackboard work',
  q6  TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Usage of real world examples and case studies',
  q7  TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Clarification of doubts and student interactions',
  q8  TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Subject knowledge',
  q9  TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Class atmosphere',
  q10 TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Encourages student participation in discussions',

  sentiment       ENUM('positive','neutral','negative') NOT NULL DEFAULT 'neutral',
  sentiment_score FLOAT            DEFAULT 0.0,
  sentiment_source ENUM('rule','ml') DEFAULT 'rule',
  created_at      DATETIME         DEFAULT CURRENT_TIMESTAMP,

  INDEX idx_course     (course),
  INDEX idx_instructor (instructor),
  INDEX idx_sentiment  (sentiment),
  INDEX idx_category   (category),
  INDEX idx_created    (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ─── Seed Users ───────────────────────────────────────────────────────────────
-- Passwords are bcrypt hashes generated by setup-db.js, these are placeholders
-- The actual seeding with hashed passwords happens in setup-db.js
-- No seed feedback data — database starts empty
